import {StyleSheet} from 'react-native';

const flatListstyles = StyleSheet.create({
  safeAreaView: {
    flex: 1,
    backgroundColor: 'green',
  },
  container: {
    flexDirection: 'row',
    padding: 20,
    alignItems: 'center',
    width: '100%',
  },
  listItemView: {
    paddingVertical: 8,
    width: '100%',
  },
  addbuttonView: {
    width: '100%',
    flexDirection: 'row',
  },
  moreIconImg: {
    height: 50,
    width: 50,
  },
  flatListWrapper: {
    flex: 1,
    backgroundColor: 'white',
  },
  detailWrapper: {
    flexDirection: 'row',
    marginTop: 20,
    width: 230,
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  arrowStyle: {
    width: 40,
    height: 40,
    position: 'absolute',
    borderRadius: 8,
    left: 10,
    justifyContent: 'center',
    alignItems: 'center',
  },
  filterStyle: {
    width: 20,
    height: 20,
    right: 40,
    position: 'absolute',
  },
  textStyle: {
    color: 'white',
    alignSelf: 'center',
    fontSize: 16,
    fontWeight: 'bold',
    marginLeft: 30,
  },
  listItem: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 8,
    borderBottomWidth: 1,
    borderBottomColor: '#ccc',
  },
  image: {
    width: 60,
    height: 60,
    marginRight: 16,
    borderRadius: 4,
    borderWidth: 2,
    borderColor: '#b7b7b7',
  },
  text: {
    fontSize: 14,
    marginRight: '48%',
    color: 'black',
  },
  addButton: {
    backgroundColor: 'green',
    borderRadius: 20,
    position: 'absolute',
    right: 10,
    top: 6,
    paddingHorizontal: 25,
    paddingVertical: 4,
    zIndex: 1,
    elevation: 1,
  },
  addButtonText: {
    color: 'white',
    alignSelf: 'center',
  },
  touchableOpacityView: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    borderRadius: 20,
    position: 'absolute',
    right: 10,
    top: 6,
    overflow: 'hidden',
    zIndex: 1,
    elevation: 1,
  },
  smallText: {
    fontSize: 9,
    paddingLeft: 9,
    alignSelf: 'center',
    color: 'black',
  },
  addMinusButton: {
    backgroundColor: 'green',
    width: 30,
    justifyContent: 'center',
    alignItems: 'center',
  },
  counterText: {
    backgroundColor: '#b7b7b7',
    alignItems: 'center',
    justifyContent: 'center',
    padding: 5,
    color: 'black',
  },
  footerStyle: {
    position: 'absolute',
    backgroundColor: '#fbd01e',
    bottom: 0,
    height: 70,
    width: '100%',
    flexDirection: 'row',
  },
  amountTextStyle: {color: 'black', fontSize: 18, fontWeight: 'bold'},
  totalAmountTextView: {
    backgroundColor: '#f5c80d',
    width: '30%',
    height: '100%',
    justifyContent: 'center',
    alignItems: 'center',
  },
  searchIconStyle: {
    width: 22,
    height: 22,
    right: 10,
    alignItems: 'center',
    position: 'absolute',
    tintColor: 'white',
  },
  viewCart: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    width: '70%',
  },
  rightArrowStyle: {
    height: 30,
    width: 30,
    alignSelf: 'center',
    marginLeft: 10,
  },
  flatListContainerStyle: {
    paddingHorizontal: 12,
    paddingBottom: 60,
  },
  viewCartTextStyle: {
    fontSize: 18,
  },
});

export default flatListstyles;
